require("backend/local_backend/backend_manager_local")
require("backend/local_backend/backend_quests_local")
require("backend/local_backend/backend_boons_local")
require("backend/local_backend/default_local_backend_data")
require("backend/local_backend/script_backend_item_local")
require("backend/local_backend/script_backend_profile_attribute_local")
require("backend/local_backend/be_queue_item_local")
require("backend/local_backend/forge_tester")
require("backend/local_backend/dice_tester")
require("backend/local_backend/pray_for_loot_tester")
require("backend/local_backend/test_scripts")
require("backend/item_server/1001/dice_1001_3/dice_data_1001_3")
require("backend/local_backend/dice_game_local")
require("backend/item_server/1001/fuse_1001_2/fuse_params")
require("backend/item_server/1001/fuse_1001_2/fuse_data_1001_2")
require("backend/item_server/1001/fuse_1001_2/fuse_script_1001_2")

return 
